### PR TITLE
Update 14 - Interpret Models.ipynb

### PR DESCRIPTION
**Pull request by WassimAttar**
Add "Create compute" paragraph

### CODE REVIEW

**Comment by WassimAttar** [comment]
The compute can't be run localy.
So a compute target in a compute cluster on Azure must be created and then used.
I took example on the other jupyter notebooks on this repo.

**Comment by madiepev** [comment]
I ran the notebook again (with a Compute Instance as per instructions), and found no issue.

**Comment by WassimAttar** [comment]
Hello,
I was able to run the notebooks from 1 to 13 localy on my laptop running ubuntu 20.04.3
I didn't use an Azure Compute instance to run the notebooks.
It worked because in the notebooks 7, 8, 10, 11 and 12 a compute target in an Azure Compute cluster was defined and used.
It's not the case with the notebook 14, therefore, this specific notebook didn't work localy on my laptop.
Adding the Compute cluster, the notebook 14 worked localy on my laptop.
I hope being clear.

**Comment by madiepev** [comment]
In the instructions for every lab we refer to the set-up you need to run the notebooks. For example for 14: https://github.com/MicrosoftLearning/mslearn-dp100/blob/main/instructions/14-interpret-models.md. 
You should not run the notebooks locally on your laptop but "locally" on a compute instance. If you follow the instructions, the notebooks will run with no issues.

**Comment by WassimAttar** [comment]
Thanks for your reply.
I understand that these jupyter notebooks are not meant to work locally on a laptop.
They are meant to work on a Compute instance on Azure.
I agree on that.
I just happily noticed that they work great locally except the 14th one and this PR is a small patch with no fundamental changes to make it work in all cases.
I'm sharing this discovery with the community.
This PR might help those who can't afford a Compute instance + Compute cluster + etc...

**Comment by madiepev** [comment]
Thanks for your contribution. However, the labs are primarily designed for the DP-100 course. In this course, students get access to the necessary resources and benefit from doing this notebook with a compute instance, as it saves time compared to using a compute cluster. So the change you propose would impact the course timing which is why we we're not merging it.

**Comment by WassimAttar** [comment]
I understand.
Thanks a lot for this tremendous amount of work on these notebooks.
They are GREAT !

**Pull request closed without merging**
